// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsuldodfeckehveqsaxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzdWxkb2RmZWNrZWh2ZXFzYXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTUzMDcsImV4cCI6MjA3MjYzMTMwN30._yQanxfG2E9Dm--GNYKMNk6WwFfTaM3xO6sqgPmzy5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});